import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import GoogleAnalytics from "@/components/GoogleAnalytics";

const poppins = Poppins({subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export const metadata = {
  title: "Piyush Patel | Portfolio",
  description: "Generated by create next app",
  icons: "/annoying.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#040d21]`}>
        <GoogleAnalytics/>
        <Providers>        
        {children}
        </Providers>
      </body>
    </html>
  );
}
