import { Poppins } from "next/font/google";
import "./globals.css";
import BgWrapper from "@/components/BgWrapper";
import SideBar from "@/components/SideBar";

const poppins = Poppins({subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]})

export const metadata = {
  title: "Piyush Patel | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <BgWrapper>
        <SideBar/>
        {children}
        </BgWrapper>
      </body>
    </html>
  );
}
